[package]
name = "merkle-mountain-range"
version = "0.1.0"
authors = ["Pascal Berrang <contact@paberr.net>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[features]
